### ISSUE TITLE
weston_4.0.0.imx and libdrm_2.4.84.imx used for mx7d

### ISSUE THREAD

**Issue by Nubosch** [Freescale/meta-freescale#10]
Is there any advantage for mx7d to use special version of weston/drm? Shouldn't this only be changed for mx7ulp?

**Comment by otavio** [comment]
It is not a matter of advantage or not. We are trying to stick, when using NXP's BSP, to the vendor components. 

If you wish to use mainline, it is very possible. Add `use-mainline-bsp` to `MACHINEOVERRIDES` and it will use the official version.
