### ISSUE TITLE
GPU rendering falls back to CPU on iMX8M-Mini

### ISSUE THREAD

**Issue by escherstair** [Freescale/meta-freescale#1029]
This is a follow-up of issue #1006

I tried to enable GPU usage for Chromium on iMX8M adding `--enable-features=UseOzonePlatform --ozone-platform=wayland` startup parameters.
It seems working (because [this CodeSandbox example](https://codesandbox.io/s/rrppl0y8l4?file=/src/App.js) runs) but the performance are poor.
Profiling the execution I see that CPU usage is near to 100% and so it seems that (for some reasons) the processor falls back on CPU rendering.
Can someone confirm that GPU hardware acceleration is fully supported on Chromium on iMX8M family?

**Comment by otavio** [comment]
@thochstein is there a pending bbappend update from NXP side?

**Comment by escherstair** [comment]
Thank you very much.

**Comment by david-sterling** [comment]
I have this problem too. I am unable to play hw accelerated video beyond dunfell. However the official NXP board 8MMINILPD4-EVK with Linux 5.10.35_2.0.0 iMX validation release and it works well so must be something in FSLC. I see Weston has been seriously reworked too from dunfell.

Appreciate your work guys, thanks. I am open to help but you should throw some docs at me before I fully grasp this shit.

**Comment by thochstein** [comment]
There's a draft here: https://github.com/Freescale/meta-freescale/pull/1053

**Comment by jwzl** [comment]
@thochstein  this patch is for which version chromium? thanks!

**Comment by otavio** [comment]
We will be closing this issue since we have no plans to keep Chromium patches without support commitment.
