### ISSUE TITLE
Failed to fetch source

### ISSUE THREAD

**Issue by nobody93** [Freescale/meta-freescale#1062]
Both honister branch and master have following error:

ERROR: u-boot-imx-2021.04-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://source.codeaurora.org/external/imx/uboot-imx.git;protocol=https;branch=lf_v2021.04')

Could anyone fix it please?

Thank you.

jupiter

**Comment by otavio** [comment]
@thochstein can you verify the Git server?

**Comment by thochstein** [comment]
It works for me. Is it still failing Jupiter?

**Comment by nobody93** [comment]
Thanks, it is back
