### ISSUE TITLE
Build failure for `imx-atf` on master and kirkstone

### ISSUE THREAD

**Issue by otavio** [Freescale/meta-freescale#1084]
Unfortunately when I went to build `core-image-weston` I ran into a build failure for `imx-atf`:

```
| plat/imx/imx8m/hab.c: In function 'imx_hab_handler':
| plat/imx/imx8m/hab.c:64:57: error: array subscript 0 is outside array bounds of 'uint32_t[0]' {aka 'unsigned int[]'} [-Werror=array-bounds]
|    64 | #define HAB_RVT_CHECK_TARGET_ARM64      ((unsigned long)*(uint32_t *)(HAB_RVT_BASE + 0x18))
|       |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

_Originally posted by @thochstein in https://github.com/Freescale/meta-freescale/issues/1080#issuecomment-1124471682_

**Comment by otavio** [comment]
@thochstein, I opened this issue so that it isn't forgotten.  It might work arounded using `-Warray-bounds`.

**Comment by MaxKrummenacher** [comment]
I assume this discussion (and eventually the patch) will fix it from within GCC:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578#c39

**Comment by thochstein** [comment]
Thanks, @MaxKrummenacher !

**Comment by MaxKrummenacher** [comment]
@thochstein 
I may have been to optimistic. The workaround described in the gcc bugzilla entry makes the error go away if the constant value casted to pointer and then dereferenced is > 4kB, i.e. > 0x1000.
Looks like the HAB_RVT_BASE is at addresses 0x0880 or 0x0900 so those false positves may still be reported.
