### ISSUE TITLE
imx53 + mesa + freedreno + wayland + video => color issue

### ISSUE THREAD

**Issue by woutervanh** [Freescale/meta-freescale#1107]
As I don't have really another place to keep track of this.
Is somebody else using freedreno + mesa + wayland + gstreamer video on imx53?
It it's using the gpu to composite, colors seems to be messed up. If running on kmssink or not-scaled (thus using hw plane, using following [patch ](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/966/diffs)), colors are correct
![Capture](https://user-images.githubusercontent.com/12512905/173355971-71ce2fb0-7bb4-44c7-9750-138e00198718.PNG)

Also, I have the impression it's not that fluent. Although it's using hardware decoding and direct memory paths in between the elements. and only 360p

**Comment by otavio** [comment]
Did you try on master?

**Comment by otavio** [comment]
Closing due inactivity.
