### ISSUE TITLE
wrong kmsdev in xorg.conf?

### ISSUE THREAD

**Issue by woutervanh** [Freescale/meta-freescale#1113]
When I build an xorg system for my imx6 platform, using mainline-bsp, I need to change the kmsdev to card1 for it to work, where the default xorg.conf defined states card0. What is defining this? Is it wrong in this repo? Or do I have something wrong in my setup?
`
meta-freescale/recipes-graphics/xorg-xserver/xserver-xf86-config/use-mainline-bsp/xorg.conf:    Option     "kmsdev"      "/dev/dri/card0"
`
`
meta-freescale/recipes-graphics/xorg-xserver/xserver-xf86-config/vf/xorg.conf:    Option      "kmsdev" "/dev/dri/card0"
`

**Comment by woutervanh** [comment]
Ok, made a pullrequest both in master and kirkstone

**Comment by otavio** [comment]
Fixed in #1114
