### ISSUE TITLE
OpenGL ES 2.x support in gstreamer1.0-plugins-base bbappend broken

### ISSUE THREAD

**Issue by dv1** [Freescale/meta-freescale#12]
The gstreamer1.0-plugins-base bbappend enables the gles2 packageconfig for imxgpu3d, but not the egl one. However, on the imx6 and imx8, both are needed for proper OpenGL ES 2.x support.

Here is the patch: https://gist.github.com/dv1/8475271a79f1dfd932132ae9251366dc

**Comment by otavio** [comment]
It has been fixed in 54cfea29b commit. Closing it.
