### ISSUE TITLE
Upgrade OP-TEE and ATF (i.MX variants)

### ISSUE THREAD

**Issue by otavio** [Freescale/meta-freescale#1263]

**Comment by MrCry0** [comment]
@otavio 
**ATF**
- master: https://github.com/Freescale/meta-freescale/pull/1283
- kirstone: https://github.com/Freescale/meta-freescale/pull/1286

**OP-TEE**
- master: https://github.com/Freescale/meta-freescale/pull/1284
- kirkstone: https://github.com/Freescale/meta-freescale/pull/1285
