### ISSUE TITLE
imx6qdlsabresd: UBOOT_CONFIG not defined if kernel-fitimage is in KERNEL_CLASSES

### ISSUE THREAD

**Issue by sebfabre** [Freescale/meta-freescale#1290]
Hello,

I am working on imx6qdlsabresd with kirkstone branch (I think we have the same issue with imx6qdlsabreauto). If kernel-fitimage is added in KERNEL_CLASSES, I have the following build errors:
_Nothing PROVIDES ‘virtual/kernel’
....
Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the imx6qdlsabresd machine configuration._

In imx6qdlsabresd.conf, UBOOT_CONFIG is only defined for uboot recipes:
_UBOOT_CONFIG:pn-u-boot-fslc ??= "sd"
UBOOT_CONFIG:pn-u-boot-imx ??= " \
    sd \
    ${@bb.utils.contains('MACHINE_FEATURES', 'optee', 'sd-optee', '', d)} \
"_
kernel-fitimage class inherits uboot-sign which inherits uboot-config. uboot-config class checks UBOOT_CONFIG and it is not defined.

https://github.com/Freescale/meta-freescale/blob/kirkstone/recipes-bsp/u-boot/libubootenv_%25.bbappend seems to manage this case but only for libubootenv.

**Comment by zandrey** [comment]
I actually stumbled upon the same issue recently, but in a bit the different context.

I guess this has to be addressed in _OE-Core_ and not in this layer, as this dependency chain is hard-coded there.

-- andrey
