### ISSUE TITLE
kernel-module-imx-gpu-viv compile error with gcc 9 and imx-kernel 4.14.98

### ISSUE THREAD

**Issue by dv1** [Freescale/meta-freescale#136]
I encountered a compile error while building kernel-module-imx-gpu-viv with kernel 4.14.98 and gcc 9. Poky, meta-freescale, meta-freescape-3rdparty, meta-openembedded are all set to the master branch.

The issue is related to stricter checks in GCC 9 for attributes. These cause compiler errors.
I managed to fix this by applying two backported patches on the imx-kernel 4.14.98. The problem is that I cannot remember where I got these two backports from anymore.

I am writing this so this issue is documented, and attaching the patches so you have something to work with.

[kernel-4.14.98-patches.zip](https://github.com/Freescale/meta-freescale/files/3422770/kernel-4.14.98-patches.zip)

**Comment by MaxKrummenacher** [comment]
Note that the two patches are backported in v4.14.124.

08aaa79ba25b include/linux/module.h: copy __init/__exit attrs to init/cleanup_module
b00c958ceb6c Compiler Attributes: add support for __copy (gcc >= 9)
