### ISSUE TITLE
Rework firmware-imx-8 recipe

### ISSUE THREAD

**Issue by otavio** [Freescale/meta-freescale#1426]
As discussed in #1414, we agreed to rework the recipe because `mx8` and `mx9` devices are using it. We need to decide the recipe name for use as it is used for boot blob generation and isn't intended to be installed inside the rootfs directly.

**Comment by otavio** [comment]
My first idea for the recipe name is `imx-boot-firmware-files`.

**Comment by thochstein** [comment]
The `SRC_URI` is not for `imx-boot` components only and include i.MX 6 support:

```
nxa21648@lsv07069:~/upstream/sources/meta-freescale/recipes-bsp/firmware-imx$ grep -r "require firmware-imx"
firmware-imx_8.18.bb:require firmware-imx-${PV}.inc
firmware-imx-8_8.18.bb:require firmware-imx-${PV}.inc
firmware-imx-8m_8.18.bb:require firmware-imx-${PV}.inc
```

**Comment by otavio** [comment]
All non-imx-boot specific files should be installed on demand and use the packages. We can share the `SRC_URI` but likely have two recipes only.
