### ISSUE TITLE
FSL_MIRROR / IMX_MIRROR offline

### ISSUE THREAD

**Issue by owestermann** [Freescale/meta-freescale#1467]
Hey,

is it just me or is FSL_MIRROR / IMX_MIRROR currently broken?
Gives me a 404 for https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/.

**Comment by thochstein** [comment]
Sorry for the trouble, I see it too. We're working on it.

**Comment by thochstein** [comment]
Actually, that is working for me. What archive is it failing on?

**Comment by otavio** [comment]
No response, so I assume it is working. Closing.
