### ISSUE TITLE
Dunfell: CodeAurora links are broken

### ISSUE THREAD

**Issue by GabeDia** [Freescale/meta-freescale#1469]
Hello,

Per https://bye.codeaurora.org/ the NXP repositories have moved to their github counterpart and thus any recipes pointing to CodeAurora are broken (linux-imx, imx-atf, gst-*). Dunfell is supported until next year - can someone fix the affected recipes?

Thanks,
Gabe

**Comment by joelsand** [comment]
I have the same issue 😞  Hope this can get fixed without too much trouble.

**Comment by GabeDia** [comment]
No it needs to be ported to dunfell - thanks @thochstein for the quick fix.
