### ISSUE TITLE
[qoriq] Build failure for qoriq-atf recipe version 2.4

### ISSUE THREAD

**Issue by otavio** [Freescale/meta-freescale#1495]
I encountered a build failure while attempting to build the `qoriq-atf` recipe version 2.4. The error message indicates that the build failed while attempting to compile the `bl2.elf` and `bl31.elf` files. The error message also contains the following warning related to `bl31.elf`: "`aarch64-oel-linux-ld.bfd: warning: [path_to_bl31.elf] has a LOAD segment with RWX permissions`".

The build fails on the following machines:

- [ ] `ls1012afrwy`
- [ ] `ls1012ardb`
- [ ] `ls1028ardb`
- [ ] `ls1043ardb`
- [ ] `ls1046afrwy`
- [ ] `ls1046ardb`
- [ ] `ls1088ardb`
- [ ] `ls1088ardb-pb`
- [ ] `ls2088ardb`
- [ ] `lx2160ardb`
- [ ] `lx2162aqds`

These machines have been broken for a long time and if no one is interested in maintaining them, it would be preferable to remove them from the repository.

This issue appears to be similar to the one fixed in https://github.com/Freescale/meta-freescale/pull/1179/commits/bac8c6af8471addb7add0d1b1ddfbbbd36bed16e.

Please advise on how to proceed with fixing the build for these machines or removing them from the repository.

**Comment by junzhuimx** [comment]
It is the because of binutils upgrade to 2.39.
Let me fix it by upgrade to the latest ATF v2.6

**Comment by otavio** [comment]
Fixed in #1500

**Comment by otavio** [comment]
@junzhuimx the fix seems incomplete. Now I have:

```
ERROR: Nothing PROVIDES 'mbedtls' (but /home/otavio/src/oe/oel/master/sources/meta-freescale/recipes-bsp/atf/qoriq-atf_2.6.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'core-image-base' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-base', 'qoriq-atf', 'mbedtls']
```

**Comment by junzhuimx** [comment]
@otavio raise another PR to fix it

**Comment by otavio** [comment]
Fixed. Thanks @junzhuimx
