### ISSUE TITLE
SCR imx-secure-enclave.git and ecdsa-lib-imx-3.3.2.3.bin mentions

### ISSUE THREAD

**Issue by Akbar-arm** [Freescale/meta-freescale#1511]
The SCR-6.1.1-1.0.0 file mentions imx-secure-enclave.git and ecdsa-lib-imx-3.3.2.3.bin but searching the repository for these returns no results. Where are they used and what are they for?

**Comment by thochstein** [comment]
Can you re-assign this to @ann-thornton? I can't assign her, nor does it seem that I can reference here in this comment.

**Comment by thochstein** [comment]
Oh, I guess I do know the answer to this. @Akbar-arm, the SCR file is also for the `meta-imx` layer. Not all recipes in `meta-imx` have been upstreamed to `meta-freescale`.
