### ISSUE TITLE
Dunfell can not be build because of missing libdrm-armada and xf86-video-armada

### ISSUE THREAD

**Issue by micky7** [Freescale/meta-freescale#1553]
Hi,

i want to build a yocto based image with x11 support based on dunfell. It fails by fetching the sources.

WARNING: libdrm-armada-0.1+gitAUTOINC+6b461c163b-r0 do_fetch: Failed to fetch URL git://git.armlinux.org.uk/~rmk/libdrm-armada.git, attempting MIRRORS if available
WARNING: xf86-video-armada-2_0.1+gitAUTOINC+78e7116a5b_8478eef32f-r0 do_fetch: Failed to fetch URL git://git.armlinux.org.uk/cgit/xf86-video-armada.git;branch=unstable-devel;protocol=http;name=armada, attempting MIRRORS if available

It seems the sources are not available any more.

HTTP request sent, awaiting response... 404 Not Found
2023-05-30 21:05:14 ERROR 404: Not Found.

I have also tried the master branch but it did not support dunfell.

Thanks Michael

[log.do_fetch.430835.tar.gz](https://github.com/Freescale/meta-freescale/files/11605849/log.do_fetch.430835.tar.gz)

**Comment by otavio** [comment]
Please check https://github.com/Freescale/meta-freescale/commit/73e068409ffe01d6c52f329f3673cc601773f774; seems it is gone.

**Comment by micky7** [comment]
clear, is there a backport planed for dunfell?

**Comment by otavio** [comment]
Please prepare a PR for it.

**Comment by otavio** [comment]
Fixed in https://github.com/Freescale/meta-freescale/commit/501032fb30abbad54616a2d9bb4555c297fc35b6
