### ISSUE TITLE
xwayland: glamor support broken on iMX8

### ISSUE THREAD

**Issue by embdur** [Freescale/meta-freescale#1561]
`Xwayland` glamor support appears to be broken on iMX8:
```
Disabling glamor and dri3 support, XWAYLAND_NO_GLAMOR is set
Failed to initialize glamor, falling back to sw
```

I found this string in `libEGL`(`imx-gpu-viv`):
```
# fgrep XWAYLAND_NO_GLAMOR /usr/lib/aarch64-linux-gnu/libEGL.so.1.5.0
grep: /usr/lib/aarch64-linux-gnu/libEGL.so.1.5.0: binary file matches
```
If we change this string to something else e.g. by using `sed`, `Xwayland` starts fine with glamor support.

This only happens when `weston` automatically launches `Xwayland` via socket. If `Xwayland` is run manually, after starting weston, the _falling back to sw_ message does not appear. If we add `-verbose 3` to `Xwayland` command line it says:
```
(II) glamor: Using GBM backend
``` 

There is no reference to Glamor on https://www.nxp.com/docs/en/user-guide/IMX_GRAPHICS_USERS_GUIDE.pdf or https://github.com/nxp-imx/imx-manifest/blob/imx-linux-kirkstone/GraphicsChangeLogv6. Does NXP even support glamor?

**Comment by thochstein** [comment]
Sorry for the trouble. I'm told that glamor was removed due to a conflict with Weston that caused an xterm hang.

We will continue to look at the issue to see if we can restore glamor in a future release.

**Comment by otavio** [comment]
As NXP binaries do not support this, there isn't much we can do. Therefore, I will be closing this issue.
