### ISSUE TITLE
Support source mirrors

### ISSUE THREAD

**Issue by liuming50** [Freescale/meta-freescale#1613]
Like OE supports source mirrors in http://downloads.yoctoproject.org/mirror/sources, shall meta-freescale also consider support a mirror server?

I am bring out this request is because we have some builds are based on older branches of meta-freescale, and quite a lot of NXP source have changed their git URLs, to give an example:

libdrm-imx URL has been changed from:

https://source.codeaurora.org/external/imx/libdrm-imx.git

to:

https://github.com/nxp-imx/libdrm-imx

this can break old builds since "https://source.codeaurora.org/external/imx/libdrm-imx.git" does not exist any more.

if we can set up a mirror server and create source folders (use bare-cloned libdrm-imx to give an example):

http://NXP/mirror/sources/git2/source.codeaurora.org.external.imx.libdrm-imx.git/

that will ensure old branches would not throw fetching errors.

**Comment by Livius90** [comment]
Workaround for this issue can be an "url insteadOf" setup in your git config.

```bash
[url "https://github.com/nxp-imx"]
    insteadOf = https://source.codeaurora.org/external/imx
```

**Comment by angolini** [comment]
When you say "mirrors" do you mean a copy of all the source code? Or do you mean a way to override the MIRRORs and SRC_URI variables?

Have you tried to use https://docs.yoctoproject.org/singleindex.html#source-mirror-s ?

**Comment by liuming50** [comment]
> Workaround for this issue can be an "url insteadOf" setup in your git config.
> 
> ```shell
> [url "https://github.com/nxp-imx"]
>     insteadOf = https://source.codeaurora.org/external/imx
> ```

Arha, good suggestion.

**Comment by liuming50** [comment]
> When you say "mirrors" do you mean a copy of all the source code? Or do you mean a way to override the MIRRORs and SRC_URI variables?
> 
> Have you tried to use https://docs.yoctoproject.org/singleindex.html#source-mirror-s ?

Yes, that's a good suggestion! PREMISSORS might be useful.
