### ISSUE TITLE
Support Yocto mickledore?

### ISSUE THREAD

**Issue by Livius90** [Freescale/meta-freescale#1626]
NXP already published mickledore meta-imx BSP layer, when will be mickledore supported in meta-freescale on GitHub?
https://github.com/nxp-imx/meta-imx/tree/mickledore-6.1.22-2.0.0

**Comment by otavio** [comment]
We already support it on the master branch and it is compatible with multiple releases.

**Comment by Livius90** [comment]
Not this is the official and professional way to support a Yocto release, you shall make a mickledore branch to support it for mickledore. When it will be done? Master barnch is master branch for developing example not for Yocto releases it is totally untrustworthy to use.

**Comment by otavio** [comment]
Please check https://github.com/Freescale/meta-freescale/discussions/1329.

**Comment by otavio** [comment]
Next branch intended is for next LTS release.

**Comment by Livius90** [comment]
answered
