### ISSUE TITLE
[Backport] Multiple boot binaries to Kirkstone

### ISSUE THREAD

**Issue by JPSGoncalves** [Freescale/meta-freescale#1658]
Is possible to backport multiple boot binaries to kirkstone? These are the changes: commit https://github.com/Freescale/meta-freescale/commit/e61f27077d7f92713d8b97a642fc2e196ba6508d and PR https://github.com/Freescale/meta-freescale/pull/1657. I tested the changes on kirkstone and are working fine.

Thank you!

**Comment by otavio** [comment]
Please prepare a PR.

**Comment by JPSGoncalves** [comment]
Opened PR https://github.com/Freescale/meta-freescale/pull/1659.

**Comment by JPSGoncalves** [comment]
I will close this as is already in PR. Thanks!

**Comment by JPSGoncalves** [comment]
I will close this as is already in PR. Thanks!
