### ISSUE TITLE
UBOOT_CONFIG_EXTRA is not set

### ISSUE THREAD

**Issue by dj-zhou-bg** [Freescale/meta-freescale#1693]
error:
```
| cp: cannot stat 'some/path/tmp-glibc/deploy/images/imx8mp-var-dart/u-boot-spl.bin-imx8mp-var-dart-': No such file or directory
```
I found it caused by the empty variable `UBOOT_CONFIG_EXTRA`.
In my build directory, I found:
```
$ find . -name u-boot-spl.bin-imx8mp-var-dart-*
./tmp-glibc/work/imx8mp_var_dart-fb-linux/u-boot-variscite/1.0-r0/deploy-u-boot-variscite/u-boot-spl.bin-imx8mp-var-dart-sd
./tmp-glibc/work/imx8mp_var_dart-fb-linux/imx-boot/1.0-r0/deploy-imx-boot/imx-boot-tools/u-boot-spl.bin-imx8mp-var-dart-sd
./tmp-glibc/deploy/images/imx8mp-var-dart/u-boot-spl.bin-imx8mp-var-dart-sd
```
So `UBOOT_CONFIG_EXTRA` should be `sd` in this case.
This change was introduced in commit `52a28a115d92c3d6a55f2cdfa4249ff499bcd2e3`.

**Comment by angolini** [comment]
let me try to reproduce it

**Comment by PanovAU** [comment]
deploy_mx8ulp() and deploy_mx8()

do_deploy() {
    deploy_${SOC_FAMILY}
    ....
        UBOOT_CONFIG_EXTRA="$type"
    ....
}

**Comment by angolini** [comment]
What is the status of this issue right now?

**Comment by dj-zhou-bg** [comment]
Basically, I have included `meta-freescale` in my yocto project, i.e., in `[build-dir]/conf/bblayers.conf` file, I have:
```
BBLAYERS ?= " \
  /some_path/poky/meta \
  /some_path/poky/meta-poky \
  /some_path/poky/meta-yocto-bsp \
  /some_path/poky/../meta-bg \
  /some_path/poky/../meta-freescale \ 
 // other layers
```
and in the machine file, i.e., `imx8mp-var-dart.conf`, I have `IMAGE_BOOTLOADER = "imx-boot"`
then build the image, which inherit from `core-image`, then I will get that error.

**Comment by angolini** [comment]
Can you, please, test https://github.com/Freescale/meta-freescale/pull/1707?????

**Comment by dj-zhou-bg** [comment]
> Can you, please, test #1707?????

Sure. I will test it when I have a chance. Relly appreciate your help!

**Comment by JPSGoncalves** [comment]
Just my 2 cents here. I don't know if this is the same, but the problem seems to be similar to https://github.com/Freescale/meta-freescale/issues/1664. At least at that time, imx-boot.bbappend from meta-variscite-bsp-imx was changing the do_compile() of meta-freescale and not setting  UBOOT_CONFIG_EXTRA.

**Comment by dj-zhou** [comment]
> Just my 2 cents here. I don't know if this is the same, but the problem seems to be similar to #1664. At least at that time, imx-boot.bbappend from meta-variscite-bsp-imx was changing the do_compile() of meta-freescale and not setting UBOOT_CONFIG_EXTRA.

Adding `UBOOT_CONFIG_EXTRA ??= "sd"` to the machine file caused another problem: 
```
imx8mp -> /path/to/tmp-glibc/work/var_dart_imx8mp-robotics-linux/imx-boot/1.0-r0/git/iMX8M
| NOTE: Copy ddr_firmware: lpddr4_pmu_train_2d_imem_202006.bin from /path/to/tmp-glibc/deploy/images/var-dart-imx8mp -> /path/to/tmp-glibc/work/var_dart_imx8mp-robotics-linux/imx-boot/1.0-r0/git/iMX8M
| cp: -r not specified; omitting directory '/path/to/tmp-glibc/deploy/images/var-dart-imx8mp/imx-boot-tools/'
| WARNING: exit code 1 from a shell command.
```
I am not sure if it is related to this issue.
-- I used the kirkstone branch of `meta-freescale`.

**Comment by angolini** [comment]
I don't think the PR will work on kirkstone. I don't remember to have the other PR backported

**Comment by dj-zhou** [comment]
> Can you, please, test #1707?????

I cherry-picked on your branch of this PR, I got the same error as https://github.com/Freescale/meta-freescale/issues/1693#issuecomment-1867998515

**Comment by dj-zhou** [comment]
> I don't think the PR will work on kirkstone. I don't remember to have the other PR backported

I cannot test on the `master` branches right now, just too many other errors.

**Comment by dj-zhou** [comment]
> commit `52a28a115d92c3d6a55f2cdfa4249ff499bcd2e3`.

this commit introduced the error, and it is on the `kirkstone` branch.

**Comment by angolini** [comment]
Ok, let me review the Kirkstone branch as well.
