### ISSUE TITLE
build issue on imx8mp-lpddr4-evk machine

### ISSUE THREAD

**Issue by dylad** [Freescale/meta-freescale#1704]
With lastest master branch, `imx8mp-lpddr4-evk` machine cannot build its kernel (`linux-fslc-imx`) because of a missing device-tree (`imx8mp-evk-sof-pdm.dtb`) introduces by #1667.
I am now wondering if this device-tree should be removed from `imx8mp-lpddr4-evk.conf` or if it must be added to `linux-fslc-imx` ?

**Comment by angolini** [comment]
Could you, please, send a patch removing it from the KERNEL_DEVICETREE?
