### ISSUE TITLE
Gtk+3 got error with xwayland distro

### ISSUE THREAD

**Issue by NguyenTrongThinh** [Freescale/meta-freescale#180]
I use fsl-xwayland distro [here](https://github.com/Freescale/meta-freescale-distro/blob/master/conf/distro/fsl-xwayland.conf). I bitbake core-image-sato but I got error while building matchbox-panel

configure: WARNING: using cross tools not prefixed with host triplet
checking pkg-config is at least version 0.9.0... yes
checking for MATCHBOX_PANEL... no
configure: error: Package requirements (glib-2.0
                  gmodule-export-2.0
                  x11
                  gdk-x11-3.0
                  **gtk+-3.0) were not met:**
**No package 'gdk-x11-3.0' found**

I found that there is PACKAGECONFIG_remove in file meta-freescale/recipes-graphics/gtk+/gtk+3_%.bbappend

DEPENDS_append_imxgpu2d = " virtual/egl"

PACKAGECONFIG_remove_imxgpu2d = " \
    ${@bb.utils.contains("DISTRO_FEATURES", "wayland", "x11", "", d)} \
"

So We can use _wayland only or x11 only_ and we can't use xwayland distro, correct me is i am wrong.

**Comment by otavio** [comment]
You can use XWayland but GTK would use Wayland.
