### ISSUE TITLE
DP/eDP port support on imx8mq

### ISSUE THREAD

**Issue by agherzan** [Freescale/meta-freescale#184]
I saw that the current kernel revision for imx8mq seems to have support for DP in `imx-hdp` driver. There is also a dp/edp device tree. Have you guys ever tested anything in that regard? I was looking for a board with DP but couldn't find any.

**Comment by otavio** [comment]
We did not. @thochstein is NXP aware of any?

**Comment by thochstein** [comment]
We're working on a possibility. @agherzan, in the meantime please let us know if your status changes.

**Comment by agherzan** [comment]
Since our initial request, we switched to HDMI for the time being but we are interested if that would be a possible in the future.

**Comment by otavio** [comment]
@thochstein news on this? Otherwise we could close this issue.

**Comment by thochstein** [comment]
No news. I asked again a couple of days ago but no response. I guess you can close it.
