### ISSUE TITLE
Plan to sync `master` to `scarthgap`?

### ISSUE THREAD

**Issue by Livius90** [Freescale/meta-freescale#1847]
Is there any plan to sync/backport `master` branch commits to `scarthgap` LTS branch regulary? Is it possible to somehow ignore ["recipes: Switch WORKDIR use with UNPACKDIR"](https://github.com/Freescale/meta-freescale/commit/365e9110b9ee938259c306e66a07cac4e2ddc3c0) commit? I do not know `scarthgap` can support to use this new things or not.

**Comment by otavio** [comment]
Please test #1851
