### ISSUE TITLE
Mickledore branch gone

### ISSUE THREAD

**Issue by kjeldflarup** [Freescale/meta-freescale#1868]
Any reason why the `mickledore` branch has been deleted? 
Our CI broke down after synchronizing with upstream, due to missing commits.

I know that Mickledore is EOL, but a lot of older EOL branches exists.

**Comment by otavio** [comment]
I don't remember removing it, so it was probably a mistake. What rev do you have?

**Comment by kjeldflarup** [comment]
We are using this revision

5d71d4f20f8b676fc5308141f8f5002745b7d20e meta-freescale (2.1-4066-g5d71d4f2)

**Comment by otavio** [comment]
Fixed.
