### ISSUE TITLE
What is the purpose of chromium-imx.inc?

### ISSUE THREAD

**Issue by kwavnet** [Freescale/meta-freescale#2011]
https://github.com/Freescale/meta-freescale/blob/master/dynamic-layers/chromium-browser-layer/recipes-browser/chromium/chromium-imx.inc is not referenced by anyone and point to a ~8 years old repository without any visible acitivity?

Can that be removed?

**Comment by otavio** [comment]
I'm totally fine in dropping it. If you can, submit a PR to remove it, and put in this kind of description in the commit would be very helpful.
