### ISSUE TITLE
libdrm is broken

### ISSUE THREAD

**Issue by emantec1** [Freescale/meta-freescale#292]
The codeaurora.org git appears to no longer be available resulting in building libdrm to fail

ERROR: libdrm-2.4.91.imx-r0 do_fetch: Fetcher failure for URL: 'git://source.codeaurora.org/external/imx/libdrm-imx.git;protocol=https;branch=libdrm-imx-2.4.91'. Unable to fetch URL from any source.
ERROR: libdrm-2.4.91.imx-r0 do_fetch: Function failed: base_do_fetch

**Comment by mihaix** [comment]
It's there. Try checking your network connection / proxy settings.
Or try again maybe it was some temporary downtime on codeaurora.

**Comment by otavio** [comment]
It seems no one complained anymore, closing it.

**Comment by otavio** [comment]
@thochstein

**Comment by otavio** [comment]
@iamshamiullah please get the `log.do_fetch` so it provides more information how it is failing.

**Comment by angolini** [comment]
Close due to inactivity.
