### ISSUE TITLE
Receipes that depend on libusb are broken

### ISSUE THREAD

**Issue by deinok** [Freescale/meta-freescale#35]
They should depend on "libusb1"

**Comment by angolini** [comment]
Would you mind to prepare a PR?

**Comment by deinok** [comment]
@angolini sure, just let me run a `bitbake world` 
Also, a normal PR to github.com repo is okey (Not to yoctoproject.org or via email)?

**Comment by angolini** [comment]
From meta-freescale, I was able to stop only 2 recipes with DEPENDS = "libusb"

```
recipes-bsp/mxsldr/mxsldr_git.bb:5:DEPENDS = "libusb"
recipes-devtools/imx-usb-loader/imx-usb-loader_git.bb:6:DEPENDS = "libusb"
```

Some other recipe already depends on libusb1

If you need to update some recipe from yocto or openembedded, than it's better to send the patch to the proper mailing list.

If it's meta-freescale related recipe, you can choose what you prefer. Some PR are being accepted without being sent to the community, and all the patches from the community is merged.

I'm not quite sure I fully understand your last comment, so please apologize if I'm being verbose.

**Comment by deinok** [comment]
Yep, these two are the only one that cause compilation issues.
A `bitbake world` runs well.

> I'm not quite sure I fully understand your last comment, so please apologize if I'm being verbose.

Don't worry, its just that some repositories ask contributors to follow a diferent way to send patches
