### ISSUE TITLE
dp-firmware-cadence: fetch fails after #293

### ISSUE THREAD

**Issue by schiffermtq** [Freescale/meta-freescale#360]
`dp-firmware-cadence` inherits `fsl-eula-unpack`, but LICENSE is set to "NXP-Binary-EULA", not "Proprietary", triggering the check introduced by #293.

This affects at least `master` and `zeus`.

**Comment by otavio** [comment]
Can you do a PR for master? once we merge it, we can do a backport PR.

**Comment by schiffermtq** [comment]
What is the intended solution here, which license is the correct one?

**Comment by otavio** [comment]
it is Proprietary.
