### ISSUE TITLE
Applying Qt Patch error

### ISSUE THREAD

**Issue by NguyenTrongThinh** [Freescale/meta-freescale#42]
**_ISSUES_**

NOTE: Applying patch **'0015-Add-eglfs-to-IMX-GPU.patch**' (../sources/meta-freescale/dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0015-Add-eglfs-to-IMX-GPU.patch)
**WARNING: 
Some of the context lines in patches were ignored. This can lead to incorrectly applied patches.
The context lines in the patches can be updated with devtool:**

    devtool modify <recipe>
    devtool finish --force-patch-refresh <recipe> <layer_path>

Then the updated patches and the source tree (in devtool's workspace)
should be reviewed to make sure the patches apply in the correct place
and don't introduce duplicate lines (which can, and does happen
when some of the context is ignored). Further information:
http://lists.openembedded.org/pipermail/openembedded-core/2018-March/148675.html
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10450
Details:
Applying patch 0015-Add-eglfs-to-IMX-GPU.patch
patching file mkspecs/linux-oe-g++/qmake.conf
Hunk #1 succeeded at 34 with fuzz 1 (offset -3 lines).

Now at patch 0015-Add-eglfs-to-IMX-GPU.patch
NOTE: Applying patch '**0016-Configure-eglfs-with-egl-pkg-config.patch'** (../sources/meta-freescale/dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0016-Configure-eglfs-with-egl-pkg-config.patch)
**WARNING: 
Some of the context lines in patches were ignored. This can lead to incorrectly applied patches.
The context lines in the patches can be updated with devtool:**

    devtool modify <recipe>
    devtool finish --force-patch-refresh <recipe> <layer_path>

Then the updated patches and the source tree (in devtool's workspace)
should be reviewed to make sure the patches apply in the correct place
and don't introduce duplicate lines (which can, and does happen
when some of the context is ignored). Further information:
http://lists.openembedded.org/pipermail/openembedded-core/2018-March/148675.html
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10450
Details:
Applying patch 0016-Configure-eglfs-with-egl-pkg-config.patch
patching file src/plugins/platforms/eglfs/eglfs-plugin.pro
Hunk #1 succeeded at 7 with fuzz 2 (offset 5 lines).

Now at patch 0016-Configure-eglfs-with-egl-pkg-config.patch
DEBUG: Python function patch_do_patch finished
DEBUG: Python function do_patch finished

**_ENVIRONMENT_**

1. Ubuntu 18.04
2. meta-freescale (thud)
3. meta-freescale-distro (thud)
4. meta-qt5 (thud)
5. poky (thud)
6. meta-openembedded (thud)

**_STEPS TO REPRODUCE_**

DISTRO : fslc-wayland
MACHINE: imx8mqevk
bitbake qtbase

**Comment by cyrilfr** [comment]
I have the same issue.

**Comment by NguyenTrongThinh** [comment]
I checked the content of the patch. We may not need them because all lines need to be applied are available in source code.
