### ISSUE TITLE
imx8 zeus vulkan driver error

### ISSUE THREAD

**Issue by Christian-Prather** [Freescale/meta-freescale#440]
Hello, hoping to get some assistance pointed in the right direction. I am building a yocto (zeus) image for an imx8 SOM with the vivante GPU utilizing the meta-freescale layer. I am attempting to get vulkan support on the image. I have added vulkan-loader, vulkan-header, vulkan-tools from the meta layer and the imx-gpu-viv recipe from meta-freescale. It appears that the vulkan libraries are making it on the system and I am even able to run vulkaninfo however when I do I get error VK_ERROR_INCOMPATIBLE_DRIVER. I am not sure what I am doing wrong to get support for vulkan. It also appears that I am missing an /etc/vulkan folder on the rootfs and in /usr/share/vulakan I am missing the icd.d. Any help would be amazing and greatly appreciated. Thank you in advance.

**Comment by otavio** [comment]
Please validate this error in master and dunfell. Zeus is not actively developed anymore.
