### ISSUE TITLE
Library from virtual/libg2d provided by imx-dpu-g2d requires the libdrm library for linking

### ISSUE THREAD

**Issue by dv1** [Freescale/meta-freescale#500]
If I try to link the g2d library, I get:

    ld: cannot find -ldrm

I can see that libdrm is marked as RDEPENDS in the imx-dpu-g2d recipe, but this does not solve the problem that other recipes that use G2D now have to add a special case where libdrm also must be linked in.

Can this somehow be resolved by modifying the imx-dpu-g2d recipe itself?

**Comment by otavio** [comment]
@dv1 can you check dunfell-next?

**Comment by otavio** [comment]
No feedback since September. Closing it.
