### ISSUE TITLE
Invalid version numbers in linux-fslc-imx and kernel-module-imx-gpu-viv

### ISSUE THREAD

**Issue by dv1** [Freescale/meta-freescale#521]
These recipes have version numbers like "-imx_5.4.24_2.1.0". However, underscores are not permitted in version numbers.
Yocto complains about this, reporting them as an error. Example:

    *** Error: Package name kernel-module-snd-usb-audio-5.4.70-imx_5.4.24_2.1.0+g2d1241e38347 contains illegal characters, (other than [a-z0-9.+-])

Is it safe to simply replace the underscores with dashes?

**Comment by otavio** [comment]
Which package manager?

**Comment by dv1** [comment]
ipk .

**Comment by zandrey** [comment]
Interesting, I've never caught this issue on me end...

Nevertheless, @dv1 is right - those symbols are not valid in version number.

I'm doing a merge of _5.4.71_ now and can queue this change also up, if there are no objections here. Would opt in for `-imx-5.4.24-2.1.0`, it would more-or-less match the kernel branch used by NXP.

-- andrey

**Comment by otavio** [comment]
Sure, please prepare it and send it with the PR :-)

**Comment by zandrey** [comment]
@dv1 I was trying to reproduce the issue you have with versioning, but so far I could not find any combination of `DISTRO_FEATURES` and machine to have this error pop up.

I've actually changed the versioning scheme in the `linux-fslc-imx` recipe to `-imx-5.4.24-2.1.0` as it should be (PR follows shortly), but it would be good to know what was the combination you used that triggered this behavior.

-- andrey

**Comment by zandrey** [comment]
> I believe he was using `ipk` packaging.

I have packages also configured as `PACKAGE_CLASSES = "package_ipk"` in _local.conf_ and still - I do not see the error... This is what really puzzled me and that is why I wanted to get a bit more info on the build config @dv1 is using to reproduce the issue.

**Comment by dv1** [comment]
I use current git master, and poky.

These are the layers:

    poky/meta
    meta-freescale
    meta-freescale-3rdparty
    meta-raspberrypi
    meta-qt5
    meta-openembedded/meta-multimedia
    meta-openembedded/meta-networking
    meta-openembedded/meta-gnome
    meta-openembedded/meta-python
    meta-openembedded/meta-oe
    poky/meta-poky
    poky/meta-yocto-bsp

And this is from the local.conf:

    LICENSE_FLAGS_WHITELIST = "commercial"
    PACKAGE_CLASSES = "package_ipk"
    INHERIT += "rm_work"
    RM_WORK_EXCLUDE += "virtual/kernel"
    ACCEPT_FSL_EULA = "1"

    EXTRA_IMAGE_FEATURES += "ssh-server-dropbear package-management ptest-pkgs"

    TOOLCHAIN_HOST_TASK_append = " nativesdk-meson "

    IMX_DEFAULT_BSP = "nxp"
    IMAGE_FSTYPES = "wic.gz tar.gz"

    SDK_XZ_COMPRESSION_LEVEL = "-0"
