### ISSUE TITLE
u-boot-imx-mfgtool compiled with error

### ISSUE THREAD

**Issue by NguyenTrongThinh** [Freescale/meta-freescale#53]
**My environment** 
meta-freescale: thud
meta-openembedded: thud
poky: thud
Ubuntu 18.04
**ISSUE:**
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
**| install: cannot create regular file '/home/thinhnguyen/DATA2/imx8mqevk/Yocto/build-imx8mqevk/tmp/work/imx8mqevk-imx8mqevk-linux/u-boot-imx-mfgtool/2017.03-r0/image/boot/spl/u-boot-spl.bin-imx8mqevk-mfgtool-2017.03-r0-mfgtool-2017.03-r0': No such file or directory**
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_install (log file is located at /home/thinhnguyen/DATA2/imx8mqevk/Yocto/build-imx8mqevk/tmp/work/imx8mqevk-imx8mqevk-linux/u-boot-imx-mfgtool/2017.03-r0/temp/log.do_install.12427)
ERROR: Task (/home/thinhnguyen/DATA2/imx8mqevk/Yocto/sources/meta-freescale/recipes-bsp/u-boot/**u-boot-imx-mfgtool_2017.03.bb**:do_install) failed with exit code '1'
**Reproduce Steps:**
1. Select Machine: imx8mqevk
2. Set UBOOT_CONFIG = "mfgtool"
3. bitbake u-boot-imx-mfgtool

**Comment by angolini** [comment]
Which branch?

Would you mind testing with master?

**Comment by NguyenTrongThinh** [comment]
Branch: Thud
I have not tested with master. will try

**Comment by bacol89** [comment]
I'm having the same problem. I tried on warrior and master branch.

**Comment by otavio** [comment]
@thochstein can you check this?

**Comment by thochstein** [comment]
2019?

**Comment by thochstein** [comment]
> 2019?

... and apparently still broken...

**Comment by otavio** [comment]
It seems people are not using mfgtool very often...

**Comment by angolini** [comment]
let me try to build it on master today

**Comment by thochstein** [comment]
Looks like this is the same error fixed by #825.

**Comment by otavio** [comment]
I'll consider this as fixed then. Closing.
