### ISSUE TITLE
kernel-module-imx-gpu-viv module warning

### ISSUE THREAD

**Issue by chenzilin** [Freescale/meta-freescale#54]
I got warnings when set two variable keys under branch master and rocko:

MACHINE_HAS_VIVANTE_KERNEL_DRIVER_SUPPORT = "1"
MACHINE_USES_VIVANTE_KERNEL_DRIVER_MODULE = "0"

I found the question of this and maybe resolved it:

<pre>
--- a/classes/fsl-vivante-kernel-driver-handler.bbclass
+++ b/classes/fsl-vivante-kernel-driver-handler.bbclass
@@ -41,9 +41,9 @@ python fsl_vivante_kernel_driver_handler () {
         return
 
     if use_vivante_kernel_driver_module != "1":
-        e.data.appendVar('RPROVIDES_kernel-base', ' kernel-module-imx-gpu-viv')
-        e.data.appendVar('RREPLACES_kernel-base', ' kernel-module-imx-gpu-viv')
-        e.data.appendVar('RCONFLICTS_kernel-base', ' kernel-module-imx-gpu-viv')
+        e.data.appendVar('RDEPENDS_${KERNEL_PACKAGE_NAME}-base', ' kernel-module-imx-gpu-viv')
+        e.data.appendVar('RDEPENDS_${KERNEL_PACKAGE_NAME}-base', ' kernel-module-imx-gpu-viv')
+        e.data.appendVar('RCONFLICTS_${KERNEL_PACKAGE_NAME}-base', ' kernel-module-imx-gpu-viv')
 }
</pre>

Am I right?

**Comment by otavio** [comment]
Fixed in https://github.com/Freescale/meta-freescale/commit/8413aafd59df1577b594e3553b767f165bb80b5e
