### ISSUE TITLE
ds2781_battery driver probe error

### ISSUE THREAD

**Issue by QB4-dev** [Freescale/meta-freescale#55]
Enabled w1-gpio driver for 1-wire devices, also enabled **w1_ds2781**  **ds2781_battery** drivers. Master finds ds2781 chip, but ds2781-battery driver returns **-22(EINVAL)**

```
[  849.897604] w1_master_driver w1_bus_master1: Attaching one wire slave 3d.000000a87881 crc 17
[  849.971330] ds2781-battery ds2781-battery.0.auto: failed to register battery
[  849.978650] ds2781-battery: probe of ds2781-battery.0.auto failed with error -22
```

tested on linux-fslc/4.20+gitAUTOINC+bf414f71d7-r0

**Comment by otavio** [comment]
We have a new 5.4 mainline kernel, please try and reopen if it still persists.
