### ISSUE TITLE
Adding a white-space into each (append) variable

### ISSUE THREAD

**Issue by IniterWorker** [Freescale/meta-freescale#58]
# Summary

Many append variables in meta-freescale haven't a white a the string start. According to the official documentation, all append variable require a white-space to prevent the #57 problem.

### [3.1.8. Appending and Prepending (Overrid#e Style Syntax)](https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html)
B_append = " additional data"

## Question

Do you want a pull request on `sumo` branch with all replaced appended variables?

**Comment by otavio** [comment]
Sure but please check the new branches as well.

**Comment by IniterWorker** [comment]
@otavio something like that or you have any other preference.

**Comment by IniterWorker** [comment]
I forget something in the regex. I will modify my PRs in few hours @otavio

**Comment by otavio** [comment]
All PR were applied. Closing it now.
