### ISSUE TITLE
isp-imx package fail to build if GPLv3 license is blacklisted

### ISSUE THREAD

**Issue by zandrey** [Freescale/meta-freescale#654]
PR #653 brings `bash` in `RDEPENDS` for `isp-imx` package, which would fail to build if `GPLv3` license is blacklisted.

Scripts should be made shell-neutral, otherwise this package cannot be included in images with _no-GPLv3_ setup.

@chrisdimich Can you have a look to see how scripts provided by this package could be clean-up from bashism?

-- andrey

**Comment by chrisdimich** [comment]
Yes, will do.

**Comment by chrisdimich** [comment]
Fixed by #655
