### ISSUE TITLE
Error building extensible SDK (eSDK) for i.MX with mainline BSP on Dunfell

### ISSUE THREAD

**Issue by fschrempf** [Freescale/meta-freescale#657]
Machines using the mainline BSP setup fail to build the eSDK. The issue can be reproduced with the following setup in `local.conf` and by running `bitbake core-image-minimal -c populate_sdk_ext`.

```
DISTRO = "poky"
MACHINE = "imx6ullevk"
CORE_IMAGE_EXTRA_INSTALL = "packagegroup-base"
```

The error is about a conflict between packages firmware-imx and linux-firmware. For some reason the eSDK build pulls in the firmware-imx package, which I guess it shouldn't do. This issue only occurs with the eSDK build. Building the standard SDK or any target image builds are successful.

```
ERROR: core-image-minimal-1.0-r0 do_sdk_depends: The file /lib/firmware/imx/sdma/sdma-imx6q.bin is installed by both linux-firmware and firmware-imx, aborting
ERROR: Logfile of failure stored in: [...]/tmp/work/imx6ullevk-poky-linux-gnueabi/core-image-minimal/1.0-r0/temp/log.do_sdk_depends.2740117
ERROR: Task ([...]/poky/meta/recipes-core/images/core-image-minimal.bb:do_sdk_depends) failed with exit code '1'
```

**Comment by otavio** [comment]
We fixed this in https://github.com/Freescale/meta-freescale/pull/669; we'll be preparing the backports shortly.
