### ISSUE TITLE
imx-gpu-viv 6.4.3.p0.0 graphical issues with Qt

### ISSUE THREAD

**Issue by sapiippo** [Freescale/meta-freescale#672]
The 6.4.3.p0.0 version of imx-gpu-viv is having problems running Qt correctly with eglfs backend (https://bugreports.qt.io/browse/QTBUG-90486). The issue are solved with the next update (6.4.3.p1.0) that has landed in master.
Would it be possible to have that and related changes be cherry-picked to gatesgarth as well?

**Comment by otavio** [comment]
Yes, we can. Could you cook a backport PR for it?

**Comment by sapiippo** [comment]
I can attempt one.
I'm not entirely sure if gpu update alone is enough or does it require all of release 5.4.70_2.3.0 commits.

**Comment by otavio** [comment]
As people is using gatesgarth it might be good to upgrade the GPU initially.

**Comment by otavio** [comment]
Fixed in https://github.com/Freescale/meta-freescale/pull/674
