### ISSUE TITLE
Symbolic links override between general purpose and mfgtool

### ISSUE THREAD

**Issue by IniterWorker** [Freescale/meta-freescale#68]
## Actual Behavior
When I have run the mfgtool image, the symbolic links of u-boot mfgtool and the kernel mfgtool replaced the current reference of my mainline image.

## Possible Answer
- Create specific links to the last build files mfgtool (u-boot, dtb, kernel).
- Rewrite symbolic links output (u-boot, kernel).

## Specifications
  - Version: Sumo

**Comment by otavio** [comment]
Is it possible for you to confirm this on master or dunfell?

**Comment by otavio** [comment]
This is a very old issue and no body has mentioned something similar. I am closing this for now.
