### ISSUE TITLE
LOCALVERSION (and MXC_GPU_VIV) does work since dunfell

### ISSUE THREAD

**Issue by msalvinik** [Freescale/meta-freescale#707]
`CONFIG_LOCALVERSION` setting done in `fsl-kernel-localversion.bbclass` does not work anymore since dunfell, because since this release `linux-imx.inc` includes also `kernel-yocto.bbclass`.

In this class, task `kernel_configme` task overwrites the `.config` file generated by `preconfigure` task in `fsl-kernel-localversion.bbclass`

Same result for `CONFIG_MXC_GPU_VIV` set in `fsl-vivante-kernel-driver-handler.bbclass`.

**Comment by otavio** [comment]
@msalvinik, thanks for reporting the local version bug; this is now fixed. I couldn't reproduce the GPU_VIV error, and it worked fine in my tests. Please open a specific issue for it with more detail about how to reproduce it.

**Comment by msalvinik** [comment]
@otavio  I'm sorry, my mistake: you are right, GPU_VIV worked fine. Thanks for fixing LOCALVERSION.

**Comment by denix0** [comment]
This actually breaks standard capability to apply config fragments!
