### ISSUE TITLE
error bucause of 492999986124b5e960d0e21fc81d341458d6c5ad

### ISSUE THREAD

**Issue by leimaohui** [Freescale/meta-freescale#721]
I select linux-qoriq as kernel in my config file: 

PREFERRED_PROVIDER_virtual/kernel = "linux-qoriq"

And I met the following error with the latest commit of master branch: 
```
NOTE: Executing Tasks
ERROR: linux-qoriq-5.4.47+gitAUTOINC+6bff40d413-r0 do_kernel_localversion: Execution of '/ubinux-dev/fct001/fnst/ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/temp/run.do_kernel_localversion.44674' failed with exit code 2:
/ubinux-dev/ /ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/temp/run.do_kernel_localversion.44674: 162: cannot open /ubinux-dev/ ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/defconfig: No such file
WARNING: exit code 2 from a shell command.

```
I found this error will disappear without commit 492999986124b5e960d0e21fc81d341458d6c5ad:

 ```
   classes: fsl-kernel-localversion: Fix task dependency

    We need to do any change to the generated `.config` file after it is
    finished to be modified. In the case of `kernel-yocto` class being in use,
    we need to do it after `kernel_configme` task.

    Fixes: c7e23876 ("linux-imx.inc: inherit kernel-yocto class")
    Fixes: #707.
    Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
    Change-Id: I7d32b47595dff269defdc5b3f98aa0b9d89b603a
```

So, is there anything wrong in my config? Or is something wrong with this this commit?

**Comment by otavio** [comment]
Hello,

Em qua., 14 de abr. de 2021 às 01:59, leimaohui
***@***.***> escreveu:
> I select linux-qoriq as kernel in my config file:
>
> PREFERRED_PROVIDER_virtual/kernel = "linux-qoriq"
>
> And I met the following error with the latest commit of master branch today.
>
> NOTE: Executing Tasks
> ERROR: linux-qoriq-5.4.47+gitAUTOINC+6bff40d413-r0 do_kernel_localversion: Execution of '/ubinux-dev/fct001/fnst/ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/temp/run.do_kernel_localversion.44674' failed with exit code 2:
> /ubinux-dev/ /ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/temp/run.do_kernel_localversion.44674: 162: cannot open /ubinux-dev/ ubinux-build/build-ubinux-armv8/tmp/work/ubinux_armv8-ubinux-linux/linux-qoriq/5.4.47+gitAUTOINC+6bff40d413-r0/defconfig: No such file
> WARNING: exit code 2 from a shell command.
>
> I found this error will disappear without commit 4929999:
>
> classes: fsl-kernel-localversion: Fix task dependency
>
> We need to do any change to the generated `.config` file after it is
> finished to be modified. In the case of `kernel-yocto` class being in use,
> we need to do it after `kernel_configme` task.
>
> Fixes: c7e23876 ("linux-imx.inc: inherit kernel-yocto class")
> Fixes: #707.
> Signed-off-by: Otavio Salvador ***@***.***>
> Change-Id: I7d32b47595dff269defdc5b3f98aa0b9d89b603a
>
> So, is there anything wrong in my config? Or is something wrong with this this commit?

It is a regression so I need to check it, please open a github issue
so we look at it.

-- 
Otavio Salvador                             O.S. Systems
http://www.ossystems.com.br        http://code.ossystems.com.br
Mobile: +55 (53) 9 9981-7854          Mobile: +1 (347) 903-9750
