### ISSUE TITLE
ERROR: ParseError at meta-freescale/recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc:32: unparsed line: '"'

### ISSUE THREAD

**Issue by embexus** [Freescale/meta-freescale#8]
https://github.com/Freescale/meta-freescale/blob/d40f4ca5fb00812af414f41c72761fad6dd5100f/recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc#L32

**Comment by grandpaul** [comment]
I met this too. There's an extra double quote " after EXTRA_PROVIDES_append_imxgpu3d in recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc

**Comment by otavio** [comment]
It has been fixed on master and sumo. Thanks for letting us know about the issue.
