### ISSUE TITLE
zeus chromuin has many bugs on imx8m mini

### ISSUE THREAD

**Issue by jwzl** [Freescale/meta-freescale#826]
1. click drop menu will crash!
2. open chromium will cause weston crash at some times, and will show black screen
3. when add --in-process-gpu, it will show black squze at some times.
4.  I found the newest yocto bsp still has this issue, and how can I fix these ?

**Comment by angolini** [comment]
We are working to include the latest BSP from NXP on master. I saw there were an update for the GPU packages.

Would you mind to test on master and report the status?

Are you using chromium-imx?
