### ISSUE TITLE
kernel-module-qca9377: build error: some undeclared symbols

### ISSUE THREAD

**Issue by angolini** [Freescale/meta-freescale#851]
Using:

```
MACHINE = 'imx8mm-lpddr4-evk'
DISTRO ?= 'fsl-framebuffer'
```
 
On master, I could face some build errors for `kernel-module-qca9377`. Maybe there is still some update missing for the latest BSP upstream?

For example:
```
|  4698 |             if(roamResult == eCSR_ROAM_RESULT_LOSTLINK) {
|       |               ^
| /.../yocto/master/build/tmp/work/imx8mm_lpddr4_evk-fsl-linux/kernel-module-qca9377/3.1-r0/git/CORE/HDD/src/wlan_hdd_assoc.c:4707:9: note: here
|  4707 |         case eCSR_ROAM_DISASSOCIATED:
|       |         ^~~~
| cc1: some warnings being treated as errors
```
or

```
| /.../yocto/master/build/tmp/work/imx8mm_lpddr4_evk-fsl-linux/kernel-module-qca9377/3.1-r0/git/CORE/SERVICES/COMMON/adf/linux/adf_os_dma_pvt.h:104:25: error: 'DMA_ATTR_NON_CONSISTENT' undeclared (first use in this function)
|   104 |                         DMA_ATTR_NON_CONSISTENT);
|       |                         ^~~~~~~~~~~~~~~~~~~~~~~
| cc1: some warnings being treated as errors
```

**Comment by thochstein** [comment]
Hi @angolini , we did drop support for this. I'll need to prepare a PR. I'm still not finished with the last release upstreaming.

**Comment by dvescovi1** [comment]
I would like to see qca-9377 support on Hardknott
This wifi is used on some iMX8MM EVK's

**Comment by angolini** [comment]
What do you mean, @dvescovi1 . As far as I know it is there in Hardknott

**Comment by thochstein** [comment]
Thanks @dvescovi1, I moved too quickly to just remove support. I will look more closely at the build break and see if I can fix that.

**Comment by thochstein** [comment]
The build break is due to incompatibility with the 5.10 kernel. I looked to update our recipe to Qualcomm's source https://source.codeaurora.org/quic/le/platform/vendor/qcom-opensource/wlan/qcacld-2.0/, but I'm told that there is not an appropriate release with this support.
