### ISSUE TITLE
Problem with MACHINEOVERRIDES_EXTENDER_FILTER_OUT

### ISSUE THREAD

**Issue by texierp** [Freescale/meta-freescale#86]
Hi @otavio ,

It seems we have a problem with the MACHINEOVERRIDES_EXTENDER_FILTER_OUT variable.

Actually, I had a doubt about the following output:

```
BB_VERSION = "1.42.0"
BUILD_SYS = "x86_64-linux"
NATIVELSBSTRING = "universal"
TARGET_SYS = "arm-poky-linux-gnueabi"
MACHINE = "imx7s-warp"
DISTRO = "poky"
DISTRO_VERSION = "2.7"
TUNE_FEATURES = "arm armv7ve vfp thumb neon callconvention-hard"
TARGET_FPU = "hard"
```

More precisely with the variable TUNE_FEATURES.

Example : 

```
$: bitbake -e core-image-base | grep '^TUNE_FEATURES'
TUNE_FEATURES="arm arm armv7ve vfp thumb neon callconvention-hard"
...
```

armv7ve seems incorrect for the mx7 family according to the imx-base file.

And now, if I comment on the variable 'MACHINEOVERRIDES_EXTENDER_FILTER_OUT_use-mainline-bsp' :

```
$: bitbake -e core-image-base | grep '^TUNE_FEATURES'
TUNE_FEATURES="arm vfp cortexa7 neon thumb callconvention-hard"
...
```

I have the right definition corresponding to the definition in the imx-base file.

The behaviour is the same for all variables.

Another example :

Without MACHINEOVERRIDES_EXTENDER_FILTER_OUT_use-mainline-bsp:

```
$: bitbake -e core-image-base | grep '^UBOOT_ENTRYPOINT'
UBOOT_ENTRYPOINT="0x80008000"
UBOOT_ENTRYPOINT_mx51="0x90008000"
UBOOT_ENTRYPOINT_mx53="0x70008000"
UBOOT_ENTRYPOINT_mx6="0x10008000"
UBOOT_ENTRYPOINT_mx6sl="0x80008000"
UBOOT_ENTRYPOINT_mx6sll="0x80008000"
UBOOT_ENTRYPOINT_mx6sx="0x80008000"
UBOOT_ENTRYPOINT_mx6ul="0x10008000"
UBOOT_ENTRYPOINT_mx6ull="0x10008000"
UBOOT_ENTRYPOINT_mx7="0x80008000"
UBOOT_ENTRYPOINT_mx8mq="0x4048000000"
UBOOT_ENTRYPOINT_mxs="0x40008000"
UBOOT_ENTRYPOINT_vf="0x80008000"
```

with MACHINEOVERRIDES_EXTENDER_FILTER_OUT_use-mainline-bsp :

```
$: bitbake -e core-image-base | grep '^UBOOT_ENTRYPOINT'
UBOOT_ENTRYPOINT_mx51="0x90008000"
UBOOT_ENTRYPOINT_mx53="0x70008000"
UBOOT_ENTRYPOINT_mx6="0x10008000"
UBOOT_ENTRYPOINT_mx6sl="0x80008000"
UBOOT_ENTRYPOINT_mx6sll="0x80008000"
UBOOT_ENTRYPOINT_mx6sx="0x80008000"
UBOOT_ENTRYPOINT_mx6ul="0x10008000"
UBOOT_ENTRYPOINT_mx6ull="0x10008000"
UBOOT_ENTRYPOINT_mx7="0x80008000"
UBOOT_ENTRYPOINT_mx8mq="0x40480000"
UBOOT_ENTRYPOINT_mxs="0x40008000"
UBOOT_ENTRYPOINT_vf="0x80008000"
```

So no UBOOT_ENTRYPOINT defined in fact.

Any idea ?

Thanks

/Pierre-Jean

**Comment by otavio** [comment]
Hello, I am wondering what you believe is wrong here?

The tune is using the NXP-specific overrides so for a mainline machine it won't be applied. This can be seen at:
https://github.com/Freescale/meta-freescale/blob/ff7dbbb6ab83206e509a02039db4aad54c9cf42a/conf/machine/include/imx-base.inc#L112-L128

It seems to be doing the right choice.
