### ISSUE TITLE
build/u-boot.u-boot-fslc missing

### ISSUE THREAD

**Issue by mauzil** [Freescale/meta-freescale#874]
Hi all.
Compiling u-boot-fslc in yocto hardknott I get the error:

 cannot stat /...../build/u-boot.u-boot-fslc: No such file or directory.

I touch the file with a bbappend recipe on do_configure_append task, but I don't know the content of the file.

**Comment by angolini** [comment]
Could you, please, describe how I can reproduce the same on my side?

**Comment by mauzil** [comment]
Sorry. I solve.
The problem was an old branch in my yocto bsp
