### ISSUE TITLE
optee-os-qoriq 3.8.0: bash invalid option

### ISSUE THREAD

**Issue by tprrt** [Freescale/meta-freescale#883]
OP-TEE 3.8.0 build fails on LS1046A:

`Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 PLATFORM=ls-ls1046ardb CFG_ARM64_core=y ARCH=arm CROSS_COMPILE_core=aarch64-oe-linux- CROSS_COMPILE_ta:arm64=aarch64-oe-linux- NOWERROR=1 LDFLAGS= LIBGCC_LOCATE_CFLAGS=--sysroot=/src/build-ls1046/tmp-glibc/work/ls1046ardb-oe-linux/optee-os-qoriq/3.8+gitAUTOINC+0cb01f7f6a-r0/recipe-sysroot all CFG_TEE_TA_LOG_LEVEL=0
| /bin/bash: --: invalid option
| Usage:        /bin/bash [GNU long option] [option] ...
|       /bin/bash [GNU long option] [option] script-file ...
| GNU long options:
|       --debug
|       --debugger
|       --dump-po-strings
|       --dump-strings
|       --help
|       --init-file
|       --login
|       --noediting
|       --noprofile
|       --norc
|       --posix
|       --pretty-print
|       --rcfile
|       --restricted
|       --verbose
|       --version
| Shell options:
|       -ilrsD or -c command or -O shopt_option         (invocation only)
|       -abefhkmnptuvxBCHP or -o option
| /bin/bash: aarch64-linux-gnu-gcc: command not found
| make: *** No rule to make target 'CROSS_COMPILE_ta:arm64=aarch64-oe-linux-'.  Stop.
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/src/layers/meta-freescale/recipes-security/optee/optee-os-qoriq_3.8.0.bb:do_compile) failed with exit code '1'`

**Comment by ting-liu** [comment]
https://github.com/Freescale/meta-freescale/pull/884 fix it.
