### ISSUE TITLE
openssl: Issue when applying patch

### ISSUE THREAD

**Issue by Ossanes** [Freescale/meta-freescale#893]
image: core-image-minimal
machine: lx2160acex7
distro: fslc-framebuffer
branch: master

ERROR: openssl-3.0.0-r0 do_patch: Applying patch '0001-eng_devcrypto-add-support-for-TLS-algorithms-offload.patch' on target directory '/home/aquino/src/tests/build/tmp/work/aarch64-fslc-linux/openssl/3.0.0-r0/openssl-3.0.0'
CmdError('quilt --quiltrc /home/aquino/src/tests/build/tmp/work/aarch64-fslc-linux/openssl/3.0.0-r0/recipe-sysroot-native/etc/quiltrc push', 0, "stdout: Applying patch 0001-eng_devcrypto-add-support-for-TLS-algorithms-offload.patch\ncan't find file to patch at input line 21\nPerhaps you used the wrong -p or --strip option?\nThe text leading up to this was:\n--------------------------\n|From 501988587567b996c9c4a14239f575e77ed27791 Mon Sep 17 00:00:00 2001\n|From: Pankaj Gupta <pankaj.gupta@nxp.com>\n|Date: Fri, 20 Sep 2019 12:18:16 +0530\n|Subject: [PATCH 1/2] eng_devcrypto: add support for TLS algorithms offload\n|\n|    - aes-128-cbc-hmac-sha1\n|    - aes-256-cbc-hmac-sha1\n|\n|Requires TLS patches on cryptodev and TLS algorithm support in Linux\n|kernel driver.\n|\n|Signed-off-by: Pankaj Gupta <pankaj.gupta@nxp.com>\n|---\n| crypto/engine/eng_devcrypto.c | 265 +++++++++++++++++++++++++++++-----\n| 1 file changed, 231 insertions(+), 34 deletions(-)\n|\n|diff --git a/crypto/engine/eng_devcrypto.c b/crypto/engine/eng_devcrypto.c\n|index 49e9ce1af3..727a660e75 100644\n|--- a/crypto/engine/eng_devcrypto.c\n|+++ b/crypto/engine/eng_devcrypto.c\n--------------------------\nNo file to patch.  Skipping patch.\n8 out of 8 hunks ignored\nPatch 0001-eng_devcrypto-add-support-for-TLS-algorithms-offload.patch does not apply (enforce with -f)\n\nstderr: ")

The file `eng_devcrypto.c` was moved and renamed. Furthermore, this patch is not applyable even fixing the path.

@ting-liu

**Comment by ting-liu** [comment]
OpenSSL is upgraded to 3.0.0 in oe-core master branch. The two patches can not be applied and will not be updated to support OpenSSL 3.0.0. So we need run command 'rm recipes-connectivity/openssl/openssl_%.bbappend' when building with master branch. But honister does not have this issue.
@otavio when will meta-freescale create honister branch? The openssl bbappend needs to be removed on master branch only.
