### ISSUE TITLE
imx-vpu-hantro DWLInit() tries to open non-existent dma heap on imx8m mini

### ISSUE THREAD

**Issue by dv1** [Freescale/meta-freescale#898]
In current meta-freescale master (current HEAD at d6082e9971906fa46876dff9330a0db9060ef8ef), imx-vpu-hantro's DWLInit() fails because it tries to open "/dev/dma_heap/linux,cma-uncached", which does not exist. There's "/dev/dma_heap/linux,cma". If I set up the former as a symlink to the latter, DWLInit() works correctly.

Machine is imx8mm-lpddr4-evk .

Is this a known issue?

**Comment by angolini** [comment]
Close due to inactivity.
