### ISSUE TITLE
devregs license appears to be wrong

### ISSUE THREAD

**Issue by dargo600** [Freescale/meta-freescale#929]
Looking at:
https://github.com/Freescale/meta-freescale/blob/master/recipes-devtools/devregs/devregs_git.bb
which uses:
https://github.com/boundarydevices/devregs

There are both GPL-1 and GPL2 licenses.  Though if you look at the right side it's clearly marked as GPL-2 not GPL-1 so I think that's the license that should be used.  I'm not too clear as to why this is marked as GPL1 here.  It possibly could be a combo of both licenses as they may be compatible.

**Comment by otavio** [comment]
https://github.com/boundarydevices/devregs/issues/7

@gibsson can you ask for Troy to look at this?

**Comment by gibsson** [comment]
I fixed the project, it's now clearly GPL-2.0 as you can see in both the source file `devregs.cpp` and the `COPYING` file.

**Comment by otavio** [comment]
@gibsson can you send a PR bumping its revision, fixing it, and closing this?

**Comment by gibsson** [comment]
Here: https://github.com/Freescale/meta-freescale/pull/931

**Comment by otavio** [comment]
Closed by #931.
