### ISSUE TITLE
The compatible issue for -generic-bsp overriding

### ISSUE THREAD

**Issue by junzhuimx** [Freescale/meta-freescale#990]
The issue happens on the commit -- https://github.com/Freescale/meta-freescale/commit/30f5ce1d2168389295b4813e01898c2fb0f9bab9 
It make a lot of generic SOC overriding to be NXP BSP specific.

Recently, the a lot of recipes with "imx/mx6/mx7/mx8/mx8m" SOC overides are generic. But use "imx-generic-bsp/mx6-generix-bsp/....." to override these setting
- it is not necessary: make the recipe line longer and easy to typo
- 3rd-party/customer's meta layer can not compatible with latest changes and has no error raised by bitbake engine

**Comment by otavio** [comment]
The provided PR assist in the convertion and also provide a script to do most of it.
